name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Hugging Face Hub
        run: pip install huggingface_hub
      - name: Sync to Hugging Face Hub
        run: |
          python3 -c "from huggingface_hub import HfApi; api = HfApi(token='${{ secrets.HF_TOKEN }}'); api.upload_folder(folder_path='.', repo_id='UDAYDOMADIYA/bioaegis-api', repo_type='space', ignore_patterns=['**/node_modules/**', '**/venv/**', '.git/**', 'api/package.zip', '*.pth', '*.pkl', '__pycache__', '.next/**', '.github/**', 'data/**'])"
